name: Test Suite

on:
  push:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./projektarbeit/gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Run Unit and Instrumentation Tests
        run: cd projektarbeit && ./gradlew check connectedCheck

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: test-results
          path: projektarbeit/app/build/reports/tests
