name: Android CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./projektarbeit/gradlew

      - name: Build APK
        run: cd projektarbeit && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: App Build Artifacts
          path: |
            projektarbeit/app/build/outputs/apk/debug/app-debug.apk

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_3a
          target: google_apis
          disable-animations: true
          emulator-boot-timeout: 600
          script: cd projektarbeit && ./gradlew connectedCheck testDebugUnitTest

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Unit Test Results
          path: projektarbeit/app/build/test-results/testDebugUnitTest/
      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: UI Test Results
          path: projektarbeit/app/build/reports/androidTests/connected/

  report:
    name: Generate Test Report
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download Unit Test Results Artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: Unit Test Results
      - name: Download UI Test Results Artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: UI Test Results
      - name: Generate Test Report
        uses: dorny/test-reporter@v1.8.0
        with:
          name: Android Tests
          path: |
            **/projektarbeit/**/TEST-*.xml
          reporter: java-junit
          fail-on-error: "true"
